export const projects = {
  main: [
    {
      id: 1,
      name: "My Pexel",
      description:
        "This is my last project from a Front End Development course in start2impact.it",
      tech: ["React", "Redux", "Firebase", "Styled Components"],
      image: "/images/projects/project-mypexel.png",
      website_link: "https://my-pexels.netlify.app/",
      github_link: "https://github.com/ThGnommy/s2i-web-final-project",
      type: "web",
    },
    {
      id: 2,
      name: "Knucklebones Clone",
      description: "My implementation of the Mini-Game Knucklebones.",
      tech: ["React", "TailwindCSS", "Vite"],
      image: "/images/projects/project-knucklebones.png",
      website_link: "https://knucklebones-react.netlify.app/",
      github_link: "https://github.com/ThGnommy/knucklebones-react",
      type: "web",
    },
    {
      id: 3,
      name: "Early Bird Times",
      description: "News Application made with React Native",
      tech: [
        "React Native",
        "Expo",
        "Redux-Toolkit",
        "Typescript",
        "NativeBase",
        "Firebase",
      ],
      image: "/images/projects/project-news-app.png",
      github_link: "https://github.com/ThGnommy/react-native-news-app",
      type: "mobile",
    },
    {
      id: 4,
      name: "Rest Countries",
      description: "A challenge by Frontend Mentor",
      tech: ["React", "TailwindCSS", "Typescript"],
      image: "/images/projects/project-restcountries.png",
      website_link: "https://quizzical-snyder-526910.netlify.app/",
      github_link: "https://github.com/ThGnommy/rest-countries",
      type: "web",
    },
    {
      id: 5,
      name: "Air Pollution Project",
      description: "A simple project using aqicn and leaflet api",
      tech: ["Javascript", "Webpack"],
      image: "/images/projects/project-pollution.png",
      website_link: "https://the-air-pollution-project.netlify.app/",
      github_link: "https://github.com/ThGnommy/s2i-air-pollution-project",
      type: "web",
    },
    {
      id: 6,
      name: "Another Weather App",
      description: "A simple project using open weather api",
      tech: ["Javascript", "Webpack", "PaperCSS"],
      image: "/images/projects/project-weather.png",
      website_link: "https://another-weather-application.netlify.app/",
      github_link: "https://github.com/ThGnommy/another-weather-app-webpack",
      type: "web",
    },
    {
      id: 7,
      name: "Portfolio",
      description: "Feel free to checkout my personal portfolio repository",
      tech: ["Next.js", "TailwindCSS", "Typescript"],
      image: "/images/projects/personal-portfolio.png",
      github_link: "https://github.com/ThGnommy/my-portfolio",
      type: "web",
    },

    {
      id: 8,
      name: "URL Shortening Landing Page",
      description: "A challenge by Frontend Mentor",
      tech: ["Next.js"],
      image: "/images/projects/project-landing-page.png",
      website_link:
        "https://url-shortening-landing-page-gn6novblf-gnommy.vercel.app/",
      github_link: "https://github.com/ThGnommy/url-shortening-landing-page",
      type: "web",
    },
    {
      id: 9,
      name: "Free From Trash",
      description:
        "App that helps to clean places from trash in a collaboration manner",
      tech: ["React Native", "Expo", "Typescript", "Magnus UI", "Firebase"],
      image: "/images/projects/project-free-from-trash.png",
      github_link: "https://github.com/ThGnommy/free-from-trash",
      type: "mobile",
    },
  ],
  other: [
    {
      id: 1,
      name: "Flappy Bird Remake",
      description: "My remake of the game Flappy Bird in Godot",
      tech: ["Godot"],
      image: "/images/other-projects/flappy-bird.gif",
      website_link: "",
      github_link: "https://github.com/ThGnommy/flappy-bird-godot",
    },
    {
      id: 2,
      name: "Tic Tac Toe",
      description: "My implementation of the game Tic Tac Toe in Lua",
      tech: ["Lua"],
      image: "/images/other-projects/tic-tac-toe.gif",
      website_link: "",
      github_link: "https://github.com/ThGnommy/lua-tic-tac-toe",
    },
  ],
};

export default projects;
