import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout/";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Thomas Brandoli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section>
          <h2 className="text-5xl font-light pb-8">hello, I'm Thomas.</h2>
          <p className="text-lg font-thin">
            I'm a web developer from Modena, Italy. I'm specializing in react
            framework
          </p>
        </section>
      </Layout>
    </div>
  );
};

export default Home;
