import { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Layout from "../components/Layout";

export const MyPens: NextPage = () => {
  const DynamicCodePens = dynamic(() => import("../components/CodePens"), {
    ssr: false,
  });

  return (
    <>
      <Head>
        <title>Thomas Brandoli | Pens</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <DynamicCodePens />
      </Layout>
    </>
  );
};

export default MyPens;
