import { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import useTitle from "../hooks/useTitle";

export const MyPens: NextPage = () => {
  const DynamicCodePens = dynamic(() => import("../components/CodePens"), {
    ssr: false,
  });

  return (
    <>
      <Head>
        <title>{useTitle()}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <DynamicCodePens />
    </>
  );
};

export default MyPens;
